### ISSUE TITLE
Coordinator source code not available?

### ISSUE THREAD

**Issue by bmcmurray** [hpx7/rtag#163]
Per the [architecture](https://docs.hathora.dev/#/architecture), any application using Hathora is connected to a Hathora-hosted coordinator at coordinator.hathora.dev, which terminates SSL and performs several other vital parts of the system operation. Is the source code for coordinators available? Can it be self-hosted?

**Comment by hpx7** [comment]
I am working on a local coordinator that will be suitable for local development. It doesn't include all the functionality of the cloud coordinator (like multi-tenancy, load balancing, automatic failover, etc), isn't high throughput, and makes security shortcuts. But these things mostly don't matter in the local development context.

You can follow along with development at https://github.com/hathora/local-coordinator

The cloud coordinator remains the choice for production deployment, but it will be easy to use the local coordinator for local development (and it will work offline). Does that answer your question?

**Comment by bmcmurray** [comment]
No, my question is really about the cloud coordinator -- it sounds as though it will have material differences to the local coordinator and if it's code isn't available that means it's a proprietary blackbox that sits in between the client and game server.

**Comment by hpx7** [comment]
The cloud coordinator source code is not available but the protocol is open -- the local coordinator can be considered a reference implementation of the Hathora protocol (so anyone is free to make their own coordinator implementation).

**Comment by hpx7** [comment]
Closing now that it's possible to configure the coordinator host: https://github.com/hathora/hathora/commit/52569fc0082b046867221d8cec033d6fd2b9b873
