### ISSUE TITLE
Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by kasbah** [hpx7/rtag#187]
Hey, I'm seeing this error since [adding a `createdBy` property to my state](https://github.com/kasbah/calm-go/commit/63e551f99be385cff0860061c15356ad5f2d6639). If I remove that property it goes away. Any ideas what that's about?

```
Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at Reader.readUInt32 (:3001/node_modules/.vite/bin-serde.js?v=c1087c99:271:31)
    at :3001/@fs/home/kaspar/projects/calm-go/code/api/types.ts:374:22
    at Array.map (<anonymous>)
    at decodeStateUpdate (:3001/@fs/home/kaspar/projects/calm-go/code/api/types.ts:373:50)
    at WebSocket.HathoraConnection.socket.onmessage (:3001/@fs/home/kaspar/projects/calm-go/code/client/.hathora/client.ts:63:63)
```

**Comment by hpx7** [comment]
I ran your `add-created-by` branch locally and I noticed that if I join as a second player there are two websocket connections to hathora established at the same time:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/5400947/156934042-6949b10c-f365-44fb-a5f5-7673e5061dbd.png">
I think this is ultimately causing issues (it's interfering with the hathora's client logic which assumes the very first message it receives is a snapshot, and the rest are updates). I would check your connection logic and make sure you only make a single connection for a given stateId per browser tab

**Comment by kasbah** [comment]
Ok yes, thanks, making sure to just have one connection seems to have fixed it.
