### ISSUE TITLE
Error on non-determinism in methods

### ISSUE THREAD

**Issue by hpx7** [hpx7/rtag#204]
Things like `Math.random()` and `Date.now()` should throw and direct the user to use `ctx.chance` and `ctx.time` instead

**Comment by Greenheart** [comment]
Quick ideas:
1. Could this perhaps be implemented by intercepting calls to `Math.random()` and `Date.now()` using a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)? Ideally, this could be added in the [`ctx` scope for each request](https://github.com/hathora/hathora/blob/66a0deb3161418975d7fd3bb283249189f5070d4/templates/base/server/.hathora/store.ts.hbs#L196), which would hopefully add the warning only for user code, but not affect the rest of the hathora server framework.

2. Or much worse: bruteforce with [fn.toString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString) and regex matching to trigger warnings.

**Comment by hpx7** [comment]
@Greenheart what do you think of the approach I took in https://github.com/hathora/hathora/pull/232?
