### ISSUE TITLE
Space bars in the path to my projects directory throws error

### ISSUE THREAD

**Issue by paccao** [hpx7/rtag#228]
The error that is thrown is ERR_MODULE_NOT_FOUND which gets called in my global install of hathora at:
AppData\Roaming\nvm\v16.14.2\node_modules\hathora\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:369

The problem was that I had spacebars in my filepath to my project folder, like this:
C:\Users\paccao\Documents\1 Code\Amongus demo\server\.hathora\

It got fixed when changed the spacebars to a dash.

**Comment by paccao** [comment]
This was replicated both on a Windows and a Mac machine, which would indicate the issue does not lie in node.js

**Comment by hpx7** [comment]
Thanks, this is now fixed in 0.7.6 (see https://github.com/hathora/hathora/commit/16c4b2ed47a174afb6a647df6aa7d0f41449b817)
