### ISSUE TITLE
Typescript errors in api/base.ts and .hathora/patch.ts

### ISSUE THREAD

**Issue by MartijnWelker** [hpx7/rtag#373]
I've been working on  a simple game and when I import `HathoraClient` from `.hathora/client` (as is done in the [ship example](https://github.com/hathora/ship-battle/blob/master/client/web/app.ts)) the web client compilation errors with typescript errors coming from `api/base.ts` and `.hathora/patch.ts`.

If required I can share more of my code, but since this errors in the automatically generated api code I'm unsure if that's needed.

Extra info:
```
$ hathora --version
0.9.12
$ node -v
v16.12.0
```

![image](https://user-images.githubusercontent.com/6674662/184489233-51b67074-946d-44e5-8956-f8030434bc5f.png)

**Comment by hpx7** [comment]
Thank you for the report @MartijnWelker. Can you try again with hathora 0.9.13 and let me know if that fixes the issue for you?

**Comment by MartijnWelker** [comment]
Yep. No more errors 👍 Thanks for the quick reply
