### ISSUE TITLE
Typed events

### ISSUE THREAD

**Issue by hpx7** [hpx7/rtag#395]
Events should be defined in the yml and potentially have data associated with them

Then you can use it like this:
```ts
ctx.sendEvent(Event.Foo, {foo: "Bar"}, userId)
```

**Comment by jyoung4242** [comment]
for both sendEvent and Broadcast Events

**Comment by jyoung4242** [comment]
any update on this?  i ran into a usage for it today

**Comment by hpx7** [comment]
No updates yet @jyoung4242. Let me know if you'd be interested in taking a stab at contributing this feature, I'd be happy to guide you through what needs to be done in hathora to make it happen.

**Comment by jyoung4242** [comment]
actually, i can try looking into it, sounds like an interesting problem to solve

**Comment by IanSSenne** [comment]
@jyoung4242 did you end up looking into this? if not i may take a stab at it as this would make one of my current projects much easier

**Comment by jyoung4242** [comment]
I'm okay with that, I'm super busy at moment... hpx7 and I have had some brief chats about what it entails... @IanSSenne

**Comment by IanSSenne** [comment]
after talking with @hpx7 this is the proposal ive come to

hathora.yml:
```yaml
SomeType:
  foo: string
events:
  myEvent: SomeType
  myOtherEvent: SomeOtherType
```
api types:
```ts
enum HathoraEvents{
  myEvent,
  myOtherEvent,
}
```
server:
```ts
ctx.sendEvent(HathoraEvents.myEvent, {foo: "bar"}, userId)
```
client:
```ts
export type HathoraEvent = {type: HathoraEvent.myEvent; val: SomeType} | {type: HathoraEvent.myOtherEvent; val: SomeOtherType}
```

**Comment by IanSSenne** [comment]
@jyoung4242 if you see any issue with this let us know :) I can't see any issues but thats not to say there arnt any

**Comment by jyoung4242** [comment]
I think it's perfect but would we consider adding this to broadcastEvents as well?

That was I don't have to loop through each client and do a sendEvent

reason i mention is 95% of time i'm using ctx.broadcastEvent

**Comment by jyoung4242** [comment]
@IanSSenne , did i lose you on my resposne?

**Comment by IanSSenne** [comment]
@jyoung4242, I'm hoping @hpx7 has an opinion on that, I'm open to looking into that as well, I got slightly busy the last day or two and haven't been able to actually start implementing it yet.

**Comment by hpx7** [comment]
Yeah for broadcast it would just be
```ts
ctx.broadcastEvent(HathoraEvents.myEvent, {foo: "bar"})
```

**Comment by jyoung4242** [comment]
@IanSSenne , yup, i'm on board... lemme know if you need any assistance... i will be traveling most of next week

**Comment by IanSSenne** [comment]
@jyoung4242 just wanted to bring you up to speed on what I have managed so far, the types for Event Type, Event Payload Type, and the Context have been updated or created using `hathora gen`, the next thing to do is client side type updates (just need to change a function signature) and the server side implementation. I may be missing something but so far its going ok.

**Comment by jyoung4242** [comment]
@IanSSenne , that's fantastic! Looking forward to testing it out

**Comment by IanSSenne** [comment]
@jyoung4242 I have a working implementation at this point, just has a couple of quarks I'm waiting to hear back from hpx7, feel free to take a look at the implementation here https://github.com/IanSSenne/hathora-builder-events and let me know if you can see any glaring issues :)

**Comment by hpx7** [comment]
Fixed in https://github.com/hathora/builder/pull/418
